name: Auto Update
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  updateware:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6

      - name: Run script
        run: |
          python main.py
          
      - name: Get time
        run: echo "NOW=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Commit and push
        uses: EndBug/add-and-commit@v10
        with:
          message: "Update ${{ env.NOW }}"
